openapi: 3.0.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /topsecret:
    post:
      summary: obtains the location and the emited message of the ship
      operationId: obtainDataShip
      requestBody:
        description: satellites
        required: true
        content:
          aplication/json:
            schema:
              type: object
              title: dataShipRequest
              properties:
                satellites:
                  type: array
                  items:
                    $ref: '#/components/schemas/Satellite'
      responses:
        200:
          description: Ok
          content:
            aplication/json:
              schema:
                type: object
                title: dataShipResponse
                properties:
                  position:
                    $ref: '#/components/schemas/Position'
                  message:
                    type: string
        404:
          description: The message or the possition couldn't be determinated
  /topsecret_split:
    post:
      summary: receives different parts of the message
        operationId: receiveDataShip
        requestBody:
          description: informationSplit
          required: true
          content:
            aplication/json:
              schema:
                type: object
                title: dataShipRequest
                properties:
                  satellites:
                    type: array
                    items:
                      $ref: '#/components/schemas/Satellite'
components:
  schemas:
    Satellite:
      type: object
      properties:
        name:
          type: string
        distance:
          type: number
          format: float
        message:
          type: array
          items:
            type: string
    Position:
      type: object
      properties:
        x:
          type: number
          format: float
        y:
          type: number
          format: float





  
